### PR TITLE
Remove `matchType`

### PR DESCRIPTION
**Pull request by ayuishii**
Discussion: https://github.com/WICG/cookie-store/issues/128
Implementation tracking: https://crbug.com/1124497

***
<a href="https://pr-preview.s3.amazonaws.com/ayuishii/cookie-store/pull/167.html" title="Last updated on Sep 3, 2020, 9:42 PM UTC (28d876a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/cookie-store/167/035ad0f...ayuishii:28d876a.html" title="Last updated on Sep 3, 2020, 9:42 PM UTC (28d876a)">Diff</a>

### CODE REVIEW

**Review by inexorabletash — APPROVED** [review]
lgtm...

We may want to add a note somewhere that {name} is passed as an options dict rather than just as a string argument to allow future flexibility. It might be good to get domenic's feedback on that, though.

**Comment by ayuishii** [comment]
@inexorabletash Just to understand better, do you mean removing `get(USVString name)` variant and only accepting options for future flexibility and keeping the CookieStoreGetOptions variant available for `Window`? 

(Sorry, I noticed this PR itself is incomplete as I forgot to add simplification of `Window` exposure suggested in the [issue](https://github.com/WICG/cookie-store/issues/128_.))

/cc @domenic

**Comment by domenic** [comment]
I think the simple `get(USVString name)` variant is a good thing to keep. At the same time, you need to keep the `get(options)` variant for service workers. #128 suggest un-exposing the options variant in `Window`, but I'm not sure about that... letting people specify an explicit match URL might be useful even in Windows?

The examples should probably be updated to use the simpler string version, though.

**Comment by domenic** [comment]
> I'm not sure about that... letting people specify an explicit match URL might be useful even in Windows?

I've thought about this more and I'd like to strengthen my "I'm not sure" :). I'm really not sure whether it's useful; maybe it's safer to just leave it out. I trust you all as domain experts more than my judgment on this one.

**Comment by ayuishii** [comment]
Thanks for the feedback!

Personally I think having both options, `get(USVString name)` & `get(options)` would be nice in `Window`. Both for simplicity for the name option, and also flexibility of the options version..but curious to hear your thoughts @inexorabletash ?

**Comment by inexorabletash** [comment]
Agreed re: flexibility. And I don't think anyone will really complain. Per [priority of constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies):

Users (developers): unlikely to notice redundancy between `get(name)` & `get({name})`
Implementors: simpler to support both in both window & sw contexts
Spec authors: simpler to have single CookieStore definition

Glad we've had the discussion though!

**Comment by ayuishii** [comment]
Awesome, thanks for the discussion everyone, this was super helpful!
I updated `getAll()` example to use simple string version.

**Pull request merged**
