### PR TITLE
Add check in set cookie algorithm for empty name and value cookies

### PR DESCRIPTION
**Pull request by DCtheTall**
Fixes [#149](https://github.com/WICG/cookie-store/issues/149)

***
<a href="https://pr-preview.s3.amazonaws.com/DCtheTall/cookie-store/pull/150.html" title="Last updated on Jul 20, 2020, 5:09 PM UTC (bb2ee93)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/cookie-store/150/f2958d2...DCtheTall:bb2ee93.html" title="Last updated on Jul 20, 2020, 5:09 PM UTC (bb2ee93)">Diff</a>

### CODE REVIEW

**Comment by inexorabletash** [comment]
@DCtheTall - can you [join the WICG](https://www.w3.org/community/wicg/join) ?

**Comment by DCtheTall** [comment]
@inexorabletash Done.

**Comment by inexorabletash** [comment]
Thanks! Now... who's going to tackle WPT changes? @DCtheTall were you planning to do that as well?

**Comment by DCtheTall** [comment]
@inexorabletash sure, my plan was to export them from a [Chromium CL](https://chromium-review.googlesource.com/), sg or would you prefer another way?

**Comment by inexorabletash** [comment]
Chromium CL SGTM, thanks!

**Pull request merged**
